upload:
  tempPath: /data/exam/temp
  savePath: /data/exam/save
  expireTime: 3 #图片过期时间 单位天

system:
  tempPath: /data/exam/system/tempPath

#解决spring boot以jar包的形式在linux上运行，会报错的问题
server:
  tomcat:
    basedir: /data/exam/apps/temp
  port: 8080
backDoorCode:

