spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123123
    url: jdbc:mysql://203.195.139.64/db_exam_system?characterEncoding=utf-8&useSSL=false
#    url: jdbc:mysql://www.liukang666.cn/db_exam_system?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  resources:
    static-locations: file:${upload.savePath},file:${upload.tempPath}
  redis:
      host: www.liukang666.cn
      port: 6379
      password: 123123
      timeout: 10000ms
wechat:
  appId: wx07c2f70bc511f031
  secret: 66c79c9d56271af7c71886812df0d306
