spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: lk
    password: lk15131112...mysql_A
    url: jdbc:mysql://203.195.139.64/db_exam_system?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8
    #    url: jdbc:mysql://www.liukang666.cn/db_exam_system?characterEncoding=utf-8&useSSL=false
    hikari:
      read-only: false
      connection-timeout: 60000
      idle-timeout: 30000
      validation-timeout: 3000
      max-lifetime: 60000
      login-timeout: 5
      maximum-pool-size: 60
      minimum-idle: 10
  jpa:
    show-sql: true
    open-in-view: false
  resources:
    static-locations: file:${upload.savePath},file:${upload.tempPath}
  thymeleaf:
    cache: false
  redis:
#    host: www.liukang666.cn
#    host: 203.195.139.64
#    password: lk15131112...redis_A
    host: 39.96.212.107
    password: zsr0925Xx
    port: 6379
    timeout: 5000ms
    database: 1
    lettuce:
      shutdown-timeout: 100
      pool:
        max-idle: 8
        max-wait: 30
        min-idle: 0
        max-active: 8
#    jedis:
#      pool:
#        max-idle: 100
#        min-idle: 10
#        max-active: 30
#        max-wait: 10000ms
  data:
    redis:
      repositories:
        enabled: false
  jackson:
    time-zone: GMT+8

wechat:
  appId: wx07c2f70bc511f031
  secret: 66c79c9d56271af7c71886812df0d306

template:
  registerNotice: c3x8r484V9gzlNTxrGMDYw-IFokGNhFWpZFchAsG65k
  registerPath: /pages/index/main
